// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usuario.proto

package com.unizar.protobuf;

public final class UsuarioOuterClass {
  private UsuarioOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UsuarioOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.unizar.protobuf.Usuario)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nombre = 1;</code>
     */
    java.lang.String getNombre();
    /**
     * <code>string nombre = 1;</code>
     */
    com.google.protobuf.ByteString
        getNombreBytes();

    /**
     * <code>string correo = 2;</code>
     */
    java.lang.String getCorreo();
    /**
     * <code>string correo = 2;</code>
     */
    com.google.protobuf.ByteString
        getCorreoBytes();

    /**
     * <code>string rol = 3;</code>
     */
    java.lang.String getRol();
    /**
     * <code>string rol = 3;</code>
     */
    com.google.protobuf.ByteString
        getRolBytes();
  }
  /**
   * Protobuf type {@code com.unizar.protobuf.Usuario}
   */
  public  static final class Usuario extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.unizar.protobuf.Usuario)
      UsuarioOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Usuario.newBuilder() to construct.
    private Usuario(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Usuario() {
      nombre_ = "";
      correo_ = "";
      rol_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Usuario(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              nombre_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              correo_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              rol_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.unizar.protobuf.UsuarioOuterClass.internal_static_com_unizar_protobuf_Usuario_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.unizar.protobuf.UsuarioOuterClass.internal_static_com_unizar_protobuf_Usuario_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.unizar.protobuf.UsuarioOuterClass.Usuario.class, com.unizar.protobuf.UsuarioOuterClass.Usuario.Builder.class);
    }

    public static final int NOMBRE_FIELD_NUMBER = 1;
    private volatile java.lang.Object nombre_;
    /**
     * <code>string nombre = 1;</code>
     */
    public java.lang.String getNombre() {
      java.lang.Object ref = nombre_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nombre_ = s;
        return s;
      }
    }
    /**
     * <code>string nombre = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNombreBytes() {
      java.lang.Object ref = nombre_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nombre_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CORREO_FIELD_NUMBER = 2;
    private volatile java.lang.Object correo_;
    /**
     * <code>string correo = 2;</code>
     */
    public java.lang.String getCorreo() {
      java.lang.Object ref = correo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        correo_ = s;
        return s;
      }
    }
    /**
     * <code>string correo = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCorreoBytes() {
      java.lang.Object ref = correo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        correo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROL_FIELD_NUMBER = 3;
    private volatile java.lang.Object rol_;
    /**
     * <code>string rol = 3;</code>
     */
    public java.lang.String getRol() {
      java.lang.Object ref = rol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rol_ = s;
        return s;
      }
    }
    /**
     * <code>string rol = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRolBytes() {
      java.lang.Object ref = rol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNombreBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nombre_);
      }
      if (!getCorreoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, correo_);
      }
      if (!getRolBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, rol_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNombreBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nombre_);
      }
      if (!getCorreoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, correo_);
      }
      if (!getRolBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, rol_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.unizar.protobuf.UsuarioOuterClass.Usuario)) {
        return super.equals(obj);
      }
      com.unizar.protobuf.UsuarioOuterClass.Usuario other = (com.unizar.protobuf.UsuarioOuterClass.Usuario) obj;

      boolean result = true;
      result = result && getNombre()
          .equals(other.getNombre());
      result = result && getCorreo()
          .equals(other.getCorreo());
      result = result && getRol()
          .equals(other.getRol());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NOMBRE_FIELD_NUMBER;
      hash = (53 * hash) + getNombre().hashCode();
      hash = (37 * hash) + CORREO_FIELD_NUMBER;
      hash = (53 * hash) + getCorreo().hashCode();
      hash = (37 * hash) + ROL_FIELD_NUMBER;
      hash = (53 * hash) + getRol().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.unizar.protobuf.UsuarioOuterClass.Usuario parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.Usuario parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.Usuario parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.Usuario parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.Usuario parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.Usuario parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.Usuario parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.Usuario parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.Usuario parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.Usuario parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.Usuario parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.Usuario parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.unizar.protobuf.UsuarioOuterClass.Usuario prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.unizar.protobuf.Usuario}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.unizar.protobuf.Usuario)
        com.unizar.protobuf.UsuarioOuterClass.UsuarioOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.unizar.protobuf.UsuarioOuterClass.internal_static_com_unizar_protobuf_Usuario_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.unizar.protobuf.UsuarioOuterClass.internal_static_com_unizar_protobuf_Usuario_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.unizar.protobuf.UsuarioOuterClass.Usuario.class, com.unizar.protobuf.UsuarioOuterClass.Usuario.Builder.class);
      }

      // Construct using com.unizar.protobuf.UsuarioOuterClass.Usuario.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nombre_ = "";

        correo_ = "";

        rol_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.unizar.protobuf.UsuarioOuterClass.internal_static_com_unizar_protobuf_Usuario_descriptor;
      }

      @java.lang.Override
      public com.unizar.protobuf.UsuarioOuterClass.Usuario getDefaultInstanceForType() {
        return com.unizar.protobuf.UsuarioOuterClass.Usuario.getDefaultInstance();
      }

      @java.lang.Override
      public com.unizar.protobuf.UsuarioOuterClass.Usuario build() {
        com.unizar.protobuf.UsuarioOuterClass.Usuario result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.unizar.protobuf.UsuarioOuterClass.Usuario buildPartial() {
        com.unizar.protobuf.UsuarioOuterClass.Usuario result = new com.unizar.protobuf.UsuarioOuterClass.Usuario(this);
        result.nombre_ = nombre_;
        result.correo_ = correo_;
        result.rol_ = rol_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.unizar.protobuf.UsuarioOuterClass.Usuario) {
          return mergeFrom((com.unizar.protobuf.UsuarioOuterClass.Usuario)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.unizar.protobuf.UsuarioOuterClass.Usuario other) {
        if (other == com.unizar.protobuf.UsuarioOuterClass.Usuario.getDefaultInstance()) return this;
        if (!other.getNombre().isEmpty()) {
          nombre_ = other.nombre_;
          onChanged();
        }
        if (!other.getCorreo().isEmpty()) {
          correo_ = other.correo_;
          onChanged();
        }
        if (!other.getRol().isEmpty()) {
          rol_ = other.rol_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.unizar.protobuf.UsuarioOuterClass.Usuario parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.unizar.protobuf.UsuarioOuterClass.Usuario) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object nombre_ = "";
      /**
       * <code>string nombre = 1;</code>
       */
      public java.lang.String getNombre() {
        java.lang.Object ref = nombre_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nombre_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nombre = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNombreBytes() {
        java.lang.Object ref = nombre_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nombre_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nombre = 1;</code>
       */
      public Builder setNombre(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nombre_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nombre = 1;</code>
       */
      public Builder clearNombre() {
        
        nombre_ = getDefaultInstance().getNombre();
        onChanged();
        return this;
      }
      /**
       * <code>string nombre = 1;</code>
       */
      public Builder setNombreBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nombre_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object correo_ = "";
      /**
       * <code>string correo = 2;</code>
       */
      public java.lang.String getCorreo() {
        java.lang.Object ref = correo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          correo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string correo = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCorreoBytes() {
        java.lang.Object ref = correo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          correo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string correo = 2;</code>
       */
      public Builder setCorreo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        correo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string correo = 2;</code>
       */
      public Builder clearCorreo() {
        
        correo_ = getDefaultInstance().getCorreo();
        onChanged();
        return this;
      }
      /**
       * <code>string correo = 2;</code>
       */
      public Builder setCorreoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        correo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object rol_ = "";
      /**
       * <code>string rol = 3;</code>
       */
      public java.lang.String getRol() {
        java.lang.Object ref = rol_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rol_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string rol = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRolBytes() {
        java.lang.Object ref = rol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string rol = 3;</code>
       */
      public Builder setRol(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string rol = 3;</code>
       */
      public Builder clearRol() {
        
        rol_ = getDefaultInstance().getRol();
        onChanged();
        return this;
      }
      /**
       * <code>string rol = 3;</code>
       */
      public Builder setRolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rol_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.unizar.protobuf.Usuario)
    }

    // @@protoc_insertion_point(class_scope:com.unizar.protobuf.Usuario)
    private static final com.unizar.protobuf.UsuarioOuterClass.Usuario DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.unizar.protobuf.UsuarioOuterClass.Usuario();
    }

    public static com.unizar.protobuf.UsuarioOuterClass.Usuario getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Usuario>
        PARSER = new com.google.protobuf.AbstractParser<Usuario>() {
      @java.lang.Override
      public Usuario parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Usuario(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Usuario> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Usuario> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.unizar.protobuf.UsuarioOuterClass.Usuario getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CambioRolRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.unizar.protobuf.CambioRolRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string email = 1;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 1;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string nuevo_rol = 2;</code>
     */
    java.lang.String getNuevoRol();
    /**
     * <code>string nuevo_rol = 2;</code>
     */
    com.google.protobuf.ByteString
        getNuevoRolBytes();
  }
  /**
   * Protobuf type {@code com.unizar.protobuf.CambioRolRequest}
   */
  public  static final class CambioRolRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.unizar.protobuf.CambioRolRequest)
      CambioRolRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CambioRolRequest.newBuilder() to construct.
    private CambioRolRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CambioRolRequest() {
      email_ = "";
      nuevoRol_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CambioRolRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              nuevoRol_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.unizar.protobuf.UsuarioOuterClass.internal_static_com_unizar_protobuf_CambioRolRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.unizar.protobuf.UsuarioOuterClass.internal_static_com_unizar_protobuf_CambioRolRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest.class, com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest.Builder.class);
    }

    public static final int EMAIL_FIELD_NUMBER = 1;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 1;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUEVO_ROL_FIELD_NUMBER = 2;
    private volatile java.lang.Object nuevoRol_;
    /**
     * <code>string nuevo_rol = 2;</code>
     */
    public java.lang.String getNuevoRol() {
      java.lang.Object ref = nuevoRol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nuevoRol_ = s;
        return s;
      }
    }
    /**
     * <code>string nuevo_rol = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNuevoRolBytes() {
      java.lang.Object ref = nuevoRol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nuevoRol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, email_);
      }
      if (!getNuevoRolBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nuevoRol_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, email_);
      }
      if (!getNuevoRolBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nuevoRol_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest)) {
        return super.equals(obj);
      }
      com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest other = (com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest) obj;

      boolean result = true;
      result = result && getEmail()
          .equals(other.getEmail());
      result = result && getNuevoRol()
          .equals(other.getNuevoRol());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + NUEVO_ROL_FIELD_NUMBER;
      hash = (53 * hash) + getNuevoRol().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.unizar.protobuf.CambioRolRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.unizar.protobuf.CambioRolRequest)
        com.unizar.protobuf.UsuarioOuterClass.CambioRolRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.unizar.protobuf.UsuarioOuterClass.internal_static_com_unizar_protobuf_CambioRolRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.unizar.protobuf.UsuarioOuterClass.internal_static_com_unizar_protobuf_CambioRolRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest.class, com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest.Builder.class);
      }

      // Construct using com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        email_ = "";

        nuevoRol_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.unizar.protobuf.UsuarioOuterClass.internal_static_com_unizar_protobuf_CambioRolRequest_descriptor;
      }

      @java.lang.Override
      public com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest getDefaultInstanceForType() {
        return com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest build() {
        com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest buildPartial() {
        com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest result = new com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest(this);
        result.email_ = email_;
        result.nuevoRol_ = nuevoRol_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest) {
          return mergeFrom((com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest other) {
        if (other == com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest.getDefaultInstance()) return this;
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (!other.getNuevoRol().isEmpty()) {
          nuevoRol_ = other.nuevoRol_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 1;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 1;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 1;</code>
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 1;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nuevoRol_ = "";
      /**
       * <code>string nuevo_rol = 2;</code>
       */
      public java.lang.String getNuevoRol() {
        java.lang.Object ref = nuevoRol_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nuevoRol_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nuevo_rol = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNuevoRolBytes() {
        java.lang.Object ref = nuevoRol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nuevoRol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nuevo_rol = 2;</code>
       */
      public Builder setNuevoRol(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nuevoRol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nuevo_rol = 2;</code>
       */
      public Builder clearNuevoRol() {
        
        nuevoRol_ = getDefaultInstance().getNuevoRol();
        onChanged();
        return this;
      }
      /**
       * <code>string nuevo_rol = 2;</code>
       */
      public Builder setNuevoRolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nuevoRol_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.unizar.protobuf.CambioRolRequest)
    }

    // @@protoc_insertion_point(class_scope:com.unizar.protobuf.CambioRolRequest)
    private static final com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest();
    }

    public static com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CambioRolRequest>
        PARSER = new com.google.protobuf.AbstractParser<CambioRolRequest>() {
      @java.lang.Override
      public CambioRolRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CambioRolRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CambioRolRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CambioRolRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.unizar.protobuf.UsuarioOuterClass.CambioRolRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CambioRolResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.unizar.protobuf.CambioRolResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool exitoso = 1;</code>
     */
    boolean getExitoso();

    /**
     * <code>string mensaje = 2;</code>
     */
    java.lang.String getMensaje();
    /**
     * <code>string mensaje = 2;</code>
     */
    com.google.protobuf.ByteString
        getMensajeBytes();
  }
  /**
   * Protobuf type {@code com.unizar.protobuf.CambioRolResponse}
   */
  public  static final class CambioRolResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.unizar.protobuf.CambioRolResponse)
      CambioRolResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CambioRolResponse.newBuilder() to construct.
    private CambioRolResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CambioRolResponse() {
      exitoso_ = false;
      mensaje_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CambioRolResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              exitoso_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              mensaje_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.unizar.protobuf.UsuarioOuterClass.internal_static_com_unizar_protobuf_CambioRolResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.unizar.protobuf.UsuarioOuterClass.internal_static_com_unizar_protobuf_CambioRolResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse.class, com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse.Builder.class);
    }

    public static final int EXITOSO_FIELD_NUMBER = 1;
    private boolean exitoso_;
    /**
     * <code>bool exitoso = 1;</code>
     */
    public boolean getExitoso() {
      return exitoso_;
    }

    public static final int MENSAJE_FIELD_NUMBER = 2;
    private volatile java.lang.Object mensaje_;
    /**
     * <code>string mensaje = 2;</code>
     */
    public java.lang.String getMensaje() {
      java.lang.Object ref = mensaje_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mensaje_ = s;
        return s;
      }
    }
    /**
     * <code>string mensaje = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMensajeBytes() {
      java.lang.Object ref = mensaje_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mensaje_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (exitoso_ != false) {
        output.writeBool(1, exitoso_);
      }
      if (!getMensajeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mensaje_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (exitoso_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, exitoso_);
      }
      if (!getMensajeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mensaje_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse)) {
        return super.equals(obj);
      }
      com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse other = (com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse) obj;

      boolean result = true;
      result = result && (getExitoso()
          == other.getExitoso());
      result = result && getMensaje()
          .equals(other.getMensaje());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EXITOSO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getExitoso());
      hash = (37 * hash) + MENSAJE_FIELD_NUMBER;
      hash = (53 * hash) + getMensaje().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.unizar.protobuf.CambioRolResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.unizar.protobuf.CambioRolResponse)
        com.unizar.protobuf.UsuarioOuterClass.CambioRolResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.unizar.protobuf.UsuarioOuterClass.internal_static_com_unizar_protobuf_CambioRolResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.unizar.protobuf.UsuarioOuterClass.internal_static_com_unizar_protobuf_CambioRolResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse.class, com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse.Builder.class);
      }

      // Construct using com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        exitoso_ = false;

        mensaje_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.unizar.protobuf.UsuarioOuterClass.internal_static_com_unizar_protobuf_CambioRolResponse_descriptor;
      }

      @java.lang.Override
      public com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse getDefaultInstanceForType() {
        return com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse build() {
        com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse buildPartial() {
        com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse result = new com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse(this);
        result.exitoso_ = exitoso_;
        result.mensaje_ = mensaje_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse) {
          return mergeFrom((com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse other) {
        if (other == com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse.getDefaultInstance()) return this;
        if (other.getExitoso() != false) {
          setExitoso(other.getExitoso());
        }
        if (!other.getMensaje().isEmpty()) {
          mensaje_ = other.mensaje_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean exitoso_ ;
      /**
       * <code>bool exitoso = 1;</code>
       */
      public boolean getExitoso() {
        return exitoso_;
      }
      /**
       * <code>bool exitoso = 1;</code>
       */
      public Builder setExitoso(boolean value) {
        
        exitoso_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool exitoso = 1;</code>
       */
      public Builder clearExitoso() {
        
        exitoso_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object mensaje_ = "";
      /**
       * <code>string mensaje = 2;</code>
       */
      public java.lang.String getMensaje() {
        java.lang.Object ref = mensaje_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mensaje_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mensaje = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMensajeBytes() {
        java.lang.Object ref = mensaje_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mensaje_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mensaje = 2;</code>
       */
      public Builder setMensaje(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mensaje_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mensaje = 2;</code>
       */
      public Builder clearMensaje() {
        
        mensaje_ = getDefaultInstance().getMensaje();
        onChanged();
        return this;
      }
      /**
       * <code>string mensaje = 2;</code>
       */
      public Builder setMensajeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mensaje_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.unizar.protobuf.CambioRolResponse)
    }

    // @@protoc_insertion_point(class_scope:com.unizar.protobuf.CambioRolResponse)
    private static final com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse();
    }

    public static com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CambioRolResponse>
        PARSER = new com.google.protobuf.AbstractParser<CambioRolResponse>() {
      @java.lang.Override
      public CambioRolResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CambioRolResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CambioRolResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CambioRolResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.unizar.protobuf.UsuarioOuterClass.CambioRolResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_unizar_protobuf_Usuario_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_unizar_protobuf_Usuario_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_unizar_protobuf_CambioRolRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_unizar_protobuf_CambioRolRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_unizar_protobuf_CambioRolResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_unizar_protobuf_CambioRolResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rusuario.proto\022\023com.unizar.protobuf\"6\n\007" +
      "Usuario\022\016\n\006nombre\030\001 \001(\t\022\016\n\006correo\030\002 \001(\t\022" +
      "\013\n\003rol\030\003 \001(\t\"4\n\020CambioRolRequest\022\r\n\005emai" +
      "l\030\001 \001(\t\022\021\n\tnuevo_rol\030\002 \001(\t\"5\n\021CambioRolR" +
      "esponse\022\017\n\007exitoso\030\001 \001(\010\022\017\n\007mensaje\030\002 \001(" +
      "\t2p\n\021ServicioCambioRol\022[\n\nCambiarRol\022%.c" +
      "om.unizar.protobuf.CambioRolRequest\032&.co" +
      "m.unizar.protobuf.CambioRolResponseb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_unizar_protobuf_Usuario_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_unizar_protobuf_Usuario_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_unizar_protobuf_Usuario_descriptor,
        new java.lang.String[] { "Nombre", "Correo", "Rol", });
    internal_static_com_unizar_protobuf_CambioRolRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_unizar_protobuf_CambioRolRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_unizar_protobuf_CambioRolRequest_descriptor,
        new java.lang.String[] { "Email", "NuevoRol", });
    internal_static_com_unizar_protobuf_CambioRolResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_unizar_protobuf_CambioRolResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_unizar_protobuf_CambioRolResponse_descriptor,
        new java.lang.String[] { "Exitoso", "Mensaje", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
